os: Visual Studio 2015

platform: x64

install:
    - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
    - choco install strawberryperl
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - appveyor DownloadFile "http://rakudo.org/downloads/star/rakudo-star-latest-x86_64 (JIT).msi" -FileName "%APPVEYOR_BUILD_FOLDER%\rakudo.msi"
    - msiexec /i rakudo.msi /quiet /qn /norestart /log install.log
    - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%

build: off

test_script:
    - prove --ext .rakutest -v -e "perl6 -I." t/

shallow_clone: true
